### ISSUE TITLE
S3: As a Player I want to see the Field according to the Game with 16 random Pictures including my token and the corresponding picture highlighted.

### ISSUE THREAD

**Issue by dkajin** [sopra-fs21-group-17/pictures-server#10]
- [x] When the game is started the Field is set up in a “table”- like form with random 16 of the given 91 pictures.
- [x] On the top part and side Part the coordinates are shown of the corresponding row and column of the “table” of pictures.
- [x] For easier recognition the picture assigned to the player get highlighted in green.
- [x] The Token of the Player is visible displaying the coordinate of his specific picture.
- [x] The Field is visible for all Players with the same Pictures.

Priority: critical
Author: Julia
Estimate: 12h

**Comment by Olstra** [comment]
c024fb81baa308bf77b906b6bf6408c773c5bed8
