### ISSUE TITLE
implement Unsplash API in the server-side 

### ISSUE THREAD

**Issue by Olstra** [sopra-fs21-group-17/pictures-server#17]
API + Filter:
Bilder müssen einfach zum nachzeichnen sein

**time estimate:** 1.5 days

description: the backend should pull a collection of filtered pictures from the Unsplash api and save that collection in the backend so that the pictures can be easily displayed on the client side

**Comment by lakicv** [comment]
3ed13cb31d757c8734f686ab7e87100469dbcc41
